export const FETCH_POSTS_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POST_FAILURE'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const POST_POST_REQUEST = 'POST_POST_REQUEST'
export const POST_POST_SUCCESS = 'POST_POST_SUCCESS'
export const POST_POST_FAILURE = 'POST_POST_FAILURE'