export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const FETCH_USERS_DATA_REQUEST= 'FETCH_USERS_DATA_REQUEST'
export const FETCH_USERS_DATA_SUCCESS = 'FETCH_USERS_DATA_SUCCESS'
export const FETCH_USERS_DATA_FAILURE = 'FETCH_USERS_DATA_SUCCESS'

export const POST_USER_DATA_REQUEST = 'POST_USER_DATA_REQUEST'
export const POST_USER_DATA_SUCCESS = 'POST_USER_DATA_SUCCESS'
export const POST_USER_DATA_FAILURE = 'POST_USER_DATA_FAILURE'